name = "RangeNarrow"
version = "0.1.0"
keywords = ["math"]
defaultTargets = ["Certificate"]

[leanOptions]
pp.unicode.fun = true # pretty-prints `fun a ↦ b`
relaxedAutoImplicit = false
weak.linter.mathlibStandardSet = true
maxSynthPendingDepth = 3

[[require]]
name = "mathlib"
scope = "leanprover-community"
rev = "v4.33.0-rc2"

[[lean_lib]]
name = "RangeNarrow"
srcDir = "."
roots = ["MorgansArcFunction", "GFunction", "Minimiser", "MinimumValue", "Certificate"]